// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.0--rc2
// source: proto/module.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Empty message for ListModules request
type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_proto_module_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_module_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_module_proto_rawDescGZIP(), []int{0}
}

// Request message for GetModule
type ModuleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModuleRequest) Reset() {
	*x = ModuleRequest{}
	mi := &file_proto_module_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModuleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModuleRequest) ProtoMessage() {}

func (x *ModuleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_module_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModuleRequest.ProtoReflect.Descriptor instead.
func (*ModuleRequest) Descriptor() ([]byte, []int) {
	return file_proto_module_proto_rawDescGZIP(), []int{1}
}

func (x *ModuleRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

// Module message representing a learning module
type Module struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Subject       string                 `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`
	Grade         string                 `protobuf:"bytes,3,opt,name=grade,proto3" json:"grade,omitempty"`
	Chapter       string                 `protobuf:"bytes,4,opt,name=chapter,proto3" json:"chapter,omitempty"`
	ContentJson   string                 `protobuf:"bytes,5,opt,name=content_json,json=contentJson,proto3" json:"content_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Module) Reset() {
	*x = Module{}
	mi := &file_proto_module_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Module) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Module) ProtoMessage() {}

func (x *Module) ProtoReflect() protoreflect.Message {
	mi := &file_proto_module_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Module.ProtoReflect.Descriptor instead.
func (*Module) Descriptor() ([]byte, []int) {
	return file_proto_module_proto_rawDescGZIP(), []int{2}
}

func (x *Module) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Module) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *Module) GetGrade() string {
	if x != nil {
		return x.Grade
	}
	return ""
}

func (x *Module) GetChapter() string {
	if x != nil {
		return x.Chapter
	}
	return ""
}

func (x *Module) GetContentJson() string {
	if x != nil {
		return x.ContentJson
	}
	return ""
}

// List of modules
type ModuleList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Modules       []*Module              `protobuf:"bytes,1,rep,name=modules,proto3" json:"modules,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModuleList) Reset() {
	*x = ModuleList{}
	mi := &file_proto_module_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModuleList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModuleList) ProtoMessage() {}

func (x *ModuleList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_module_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModuleList.ProtoReflect.Descriptor instead.
func (*ModuleList) Descriptor() ([]byte, []int) {
	return file_proto_module_proto_rawDescGZIP(), []int{3}
}

func (x *ModuleList) GetModules() []*Module {
	if x != nil {
		return x.Modules
	}
	return nil
}

var File_proto_module_proto protoreflect.FileDescriptor

const file_proto_module_proto_rawDesc = "" +
	"\n" +
	"\x12proto/module.proto\x12\x06module\"\a\n" +
	"\x05Empty\"\x1f\n" +
	"\rModuleRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"\x85\x01\n" +
	"\x06Module\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x18\n" +
	"\asubject\x18\x02 \x01(\tR\asubject\x12\x14\n" +
	"\x05grade\x18\x03 \x01(\tR\x05grade\x12\x18\n" +
	"\achapter\x18\x04 \x01(\tR\achapter\x12!\n" +
	"\fcontent_json\x18\x05 \x01(\tR\vcontentJson\"6\n" +
	"\n" +
	"ModuleList\x12(\n" +
	"\amodules\x18\x01 \x03(\v2\x0e.module.ModuleR\amodules2y\n" +
	"\rModuleService\x122\n" +
	"\vListModules\x12\r.module.Empty\x1a\x12.module.ModuleList\"\x00\x124\n" +
	"\tGetModule\x12\x15.module.ModuleRequest\x1a\x0e.module.Module\"\x00B\x10Z\x0egrpcservice/pbb\x06proto3"

var (
	file_proto_module_proto_rawDescOnce sync.Once
	file_proto_module_proto_rawDescData []byte
)

func file_proto_module_proto_rawDescGZIP() []byte {
	file_proto_module_proto_rawDescOnce.Do(func() {
		file_proto_module_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_module_proto_rawDesc), len(file_proto_module_proto_rawDesc)))
	})
	return file_proto_module_proto_rawDescData
}

var file_proto_module_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_module_proto_goTypes = []any{
	(*Empty)(nil),         // 0: module.Empty
	(*ModuleRequest)(nil), // 1: module.ModuleRequest
	(*Module)(nil),        // 2: module.Module
	(*ModuleList)(nil),    // 3: module.ModuleList
}
var file_proto_module_proto_depIdxs = []int32{
	2, // 0: module.ModuleList.modules:type_name -> module.Module
	0, // 1: module.ModuleService.ListModules:input_type -> module.Empty
	1, // 2: module.ModuleService.GetModule:input_type -> module.ModuleRequest
	3, // 3: module.ModuleService.ListModules:output_type -> module.ModuleList
	2, // 4: module.ModuleService.GetModule:output_type -> module.Module
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_module_proto_init() }
func file_proto_module_proto_init() {
	if File_proto_module_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_module_proto_rawDesc), len(file_proto_module_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_module_proto_goTypes,
		DependencyIndexes: file_proto_module_proto_depIdxs,
		MessageInfos:      file_proto_module_proto_msgTypes,
	}.Build()
	File_proto_module_proto = out.File
	file_proto_module_proto_goTypes = nil
	file_proto_module_proto_depIdxs = nil
}
