# Generated by Django 5.2.1 on 2025-05-11 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="company",
            name="about",
        ),
        migrations.RemoveField(
            model_name="company",
            name="company_id",
        ),
        migrations.RemoveField(
            model_name="company",
            name="location",
        ),
        migrations.RemoveField(
            model_name="company",
            name="name",
        ),
        migrations.AddField(
            model_name="company",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
