# Generated by Django 5.2.1 on 2025-05-11 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_learningmodule"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Company",
        ),
    ]
